version: '3.5'
services: 
  social-client:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      SERVICE_4200_NAME: Social
    networks: 
      - social-client-network
    ports:
      - "4207:4200"
    volumes:
      - ".:/Social/usr/src/app"
      - /Social/usr/src/app/node_modules
networks:
  social-client-network:
    name: quizrt-network
    external: true