version: '3'
services: 
  social-client:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      SERVICE_4200_NAME: SocialUI
    networks: 
      - social-client-network
    # ports:
    #   - "4200"
    volumes:
      - ".:/Social/usr/src/app"
      - /Social/usr/src/app/node_modules
networks:
  social-client-network:
    name: quizrt-network
    external: true